# Generated by Django 5.1.1 on 2024-09-25 17:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='subscription_end_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='subscription_status',
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_in_days', models.IntegerField()),
                ('services', models.ManyToManyField(related_name='subscriptions', to='autodash_App.service')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='autodash_App.customer')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autodash_App.subscription')),
            ],
        ),
    ]
