# Generated by Django 5.1.1 on 2024-09-28 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0003_remove_servicerendered_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerenderedorder',
            name='worker',
        ),
        migrations.AddField(
            model_name='servicerenderedorder',
            name='workers',
            field=models.ManyToManyField(blank=True, null=True, to='autodash_App.worker'),
        ),
        migrations.AlterField(
            model_name='servicerendered',
            name='workers',
            field=models.ManyToManyField(blank=True, null=True, related_name='services_rendered', to='autodash_App.worker'),
        ),
        migrations.AlterField(
            model_name='servicerenderedorder',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_rendered', to='autodash_App.branch'),
        ),
    ]
