# Generated by Django 5.1.1 on 2024-10-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0009_revenue_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='final_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
