# Generated by Django 5.1.1 on 2024-10-04 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0017_servicerenderedorder_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customervehicle',
            name='user',
        ),
    ]
