# Generated by Django 5.1.1 on 2024-10-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0018_remove_customervehicle_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerenderedorder',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
