# Generated by Django 5.1.1 on 2024-10-05 20:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0023_worker_is_branch_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='customervehicle',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
