# Generated by Django 5.1.1 on 2024-11-16 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0025_remove_servicerenderedorder_discount_revenue_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaccount',
            name='daily_expense_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='branch',
            name='head_of_branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicerenderedorder',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('canceled', 'Canceled'), ('onCredit', 'OnCredit')], default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='autodash_App.branch')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPurchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='autodash_App.product')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_purchased', to='autodash_App.servicerenderedorder')),
            ],
        ),
    ]
