# Generated by Django 5.1.1 on 2024-11-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0026_adminaccount_daily_expense_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerenderedorder',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('canceled', 'Canceled'), ('onCredit', 'On Credit')], default='pending', max_length=50),
        ),
    ]
