# Generated by Django 5.1.2 on 2025-01-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0027_alter_servicerenderedorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerenderedorder',
            name='commission_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
