# Generated by Django 5.1.2 on 2025-02-05 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0031_productsale_batch_id_productsale_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsale',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
