# Generated by Django 5.1.1 on 2024-09-27 07:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0002_remove_customer_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerendered',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='servicerendered',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='servicerendered',
            name='customer_feedback',
        ),
        migrations.RemoveField(
            model_name='servicerendered',
            name='customer_rating',
        ),
        migrations.RemoveField(
            model_name='servicerendered',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='servicerendered',
            name='total_cost',
        ),
        migrations.CreateModel(
            name='ServiceRenderedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('canceled', 'Canceled')], default='pending', max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_feedback', models.TextField(blank=True, null=True)),
                ('customer_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('payment_method', models.CharField(blank=True, choices=[('loyalty', 'Loyalty Points'), ('subscription', 'Subscription'), ('cash', 'Cash')], max_length=50, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_rendered', to='autodash_App.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autodash_App.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autodash_App.worker')),
            ],
        ),
        migrations.AddField(
            model_name='servicerendered',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rendered', to='autodash_App.servicerenderedorder'),
        ),
    ]
