# Generated by Django 5.1.1 on 2024-10-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0006_customer_branch_customersubscription_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
