# Generated by Django 5.1.1 on 2024-10-03 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0012_servicerenderedorder_service_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerenderedorder',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerenderedorder',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='revenue',
            name='service_rendered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='autodash_App.servicerenderedorder'),
        ),
    ]
