# Generated by Django 5.1.1 on 2024-10-04 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0016_servicerenderedorder_time_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerenderedorder',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autodash_App.customervehicle'),
        ),
    ]
