# Generated by Django 5.1.1 on 2024-10-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0019_servicerenderedorder_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='final_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='servicerenderedorder',
            name='amount_paid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerenderedorder',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerenderedorder',
            name='final_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerenderedorder',
            name='total_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='worker',
            name='salary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
