# Generated by Django 5.1.1 on 2024-10-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0021_worker_is_gh_card_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_phone_number_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='pending_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
