# Generated by Django 5.1.1 on 2024-10-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0022_worker_is_phone_number_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_branch_head',
            field=models.BooleanField(default=False),
        ),
    ]
