# Generated by Django 5.1.2 on 2025-01-11 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0028_servicerenderedorder_commission_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerenderedorder',
            name='commission_amount',
        ),
    ]
