# Generated by Django 5.1.2 on 2025-02-04 09:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0030_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsale',
            name='batch_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='productsale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autodash_App.customer'),
        ),
    ]
