# Generated by Django 5.1.2 on 2025-02-14 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0032_productsale_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('negotiable', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='product',
            name='branch',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autodash_App.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='branch',
            field=models.ManyToManyField(related_name='products', to='autodash_App.branch'),
        ),
    ]
