# Generated by Django 5.1.2 on 2025-02-14 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0033_productcategory_servicecategory_product_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autodash_App.servicecategory'),
        ),
        migrations.AddField(
            model_name='servicerendered',
            name='negotiated_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
