# Generated by Django 5.1.2 on 2025-02-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0037_expense_is_recurring_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsale',
            name='date_sold',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
