# Generated by Django 5.1.2 on 2025-02-20 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0038_alter_productsale_date_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerenderedorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autodash_App.customer'),
        ),
    ]
