# Generated by Django 5.1.2 on 2025-03-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0040_servicerenderedorder_cash_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerendered',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('loyalty', 'Loyalty'), ('subscription', 'Subscription'), ('credit', 'Credit')], default='cash', max_length=20),
        ),
    ]
