# Generated by Django 5.1.2 on 2025-03-19 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0041_servicerendered_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerendered',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='servicerenderedorder',
            name='cash_paid_amount',
        ),
        migrations.RemoveField(
            model_name='servicerenderedorder',
            name='loyalty_used_amount',
        ),
        migrations.RemoveField(
            model_name='servicerenderedorder',
            name='subscription_used_amount',
        ),
    ]
