# Generated by Django 5.1.2 on 2025-03-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0042_remove_servicerendered_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubscription',
            name='used_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='servicerenderedorder',
            name='cash_paid',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='servicerenderedorder',
            name='loyalty_used',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='servicerenderedorder',
            name='subscription_used',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
