# Generated by Django 5.1.2 on 2025-04-03 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0043_customersubscription_used_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerenderedorder',
            old_name='loyalty_used',
            new_name='loyalty_points_used',
        ),
        migrations.RenameField(
            model_name='servicerenderedorder',
            old_name='subscription_used',
            new_name='subscription_amount_used',
        ),
        migrations.AddField(
            model_name='customersubscription',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autodash_App.servicerenderedorder'),
        ),
        migrations.AddField(
            model_name='servicerendered',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Loyalty Reward', 'Loyalty Reward'), ('Subscription', 'Subscription'), ('Cash', 'Cash')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='servicerenderedorder',
            name='loyalty_points_amount_deduction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerenderedorder',
            name='subscription_package_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autodash_App.customersubscription'),
        ),
        migrations.AlterField(
            model_name='customersubscription',
            name='used_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.CreateModel(
            name='CustomerSubscriptionTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_used', models.FloatField()),
                ('remaining_balance', models.FloatField()),
                ('date_used', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autodash_App.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autodash_App.servicerenderedorder')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autodash_App.customersubscription')),
            ],
        ),
    ]
