# Generated by Django 5.1.2 on 2025-04-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0044_rename_loyalty_used_servicerenderedorder_loyalty_points_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubscription',
            name='last_rollover',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customersubscription',
            name='sub_amount_remaining',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
