# Generated by Django 5.1.2 on 2025-04-05 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0045_customersubscription_last_rollover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubscription',
            name='latest_renewal_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CustomerSubscriptionRenewalTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_renewed', models.DateTimeField(auto_now_add=True)),
                ('amount_for_renewal', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autodash_App.customer')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autodash_App.customersubscription')),
            ],
        ),
    ]
