# Generated by Django 5.1.2 on 2025-05-02 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0047_servicerenderedorder_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('budget_amount', models.FloatField(default=0.0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_budgets', to='autodash_App.branch')),
            ],
            options={
                'ordering': ['weekday'],
                'unique_together': {('branch', 'weekday')},
            },
        ),
    ]
