# Generated by Django 5.1.2 on 2025-05-02 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0048_weeklybudget'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('apply_on', models.JSONField(default=list, help_text='List of weekdays (0=Mon … 6=Sun) or special dates')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autodash_App.branch')),
            ],
        ),
    ]
