# Generated by Django 5.1.2 on 2025-05-03 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0049_recurringexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('target_amount', models.FloatField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_targets', to='autodash_App.branch')),
            ],
            options={
                'ordering': ['branch__name', 'frequency'],
                'unique_together': {('branch', 'frequency')},
            },
        ),
    ]
