# Generated by Django 5.1.2 on 2025-05-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0050_salestarget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='is_branch_head',
            new_name='is_branch_admin',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('worker', 'Worker'), ('customer', 'Customer')], default='customer', max_length=50),
        ),
    ]
