# Generated by Django 5.1.2 on 2025-05-03 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0052_worker_date_of_birth_worker_ecowas_id_card_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('target_amount', models.FloatField(default=0.0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sales_targets', to='autodash_App.branch')),
            ],
            options={
                'ordering': ['branch__name', 'weekday'],
                'unique_together': {('branch', 'weekday')},
            },
        ),
    ]
