# Generated by Django 5.1.2 on 2025-06-27 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0053_dailysalestarget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='service_rendered',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='autodash_App.servicerenderedorder'),
        ),
    ]
