# Generated by Django 5.1.2 on 2025-07-01 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0054_alter_revenue_service_rendered'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerDailyAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bonus', models.FloatField(default=0.0)),
                ('deduction', models.FloatField(default=0.0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autodash_App.branch')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_adjustments', to='autodash_App.worker')),
            ],
            options={
                'ordering': ['-date', 'worker__user__last_name'],
                'unique_together': {('worker', 'date')},
            },
        ),
    ]
