# Generated by Django 5.1.2 on 2025-09-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0055_workerdailyadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerenderedorder',
            name='initial_sms_sent',
            field=models.BooleanField(default=False),
        ),
    ]
