# Generated by Django 5.1.2 on 2025-09-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0056_servicerenderedorder_initial_sms_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerenderedorder',
            name='completed_sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerenderedorder',
            name='credit_sms_sent',
            field=models.BooleanField(default=False),
        ),
    ]
