# Generated by Django 5.1.2 on 2025-09-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0057_servicerenderedorder_completed_sms_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerendered',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Loyalty Reward', 'Loyalty Reward'), ('Subscription', 'Subscription'), ('Cash', 'Cash'), ('MoMo', 'MoMo')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicerenderedorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('loyalty', 'Loyalty Points'), ('subscription', 'Subscription'), ('cash', 'Cash'), ('momo', 'MoMo')], max_length=50, null=True),
        ),
    ]
