# Generated by Django 5.1.2 on 2025-09-30 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0058_alter_servicerendered_payment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(blank=True, max_length=120, null=True)),
                ('driver_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('scheduled_at', models.DateTimeField(help_text='When the vehicle is expected in.')),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('arrived', 'Arrived'), ('canceled', 'Canceled'), ('converted', 'Converted to Service Order')], default='booked', max_length=20)),
                ('arrived_at', models.DateTimeField(blank=True, help_text='Actual time vehicle arrived.', null=True)),
                ('converted_at', models.DateTimeField(blank=True, help_text='When it became a Service Order.', null=True)),
                ('converted_to_order', models.BooleanField(default=False)),
                ('booking_reference', models.CharField(blank=True, max_length=24, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_bookings', to='autodash_App.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='autodash_App.customer')),
                ('service_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_booking', to='autodash_App.servicerenderedorder')),
                ('services', models.ManyToManyField(related_name='bookings', to='autodash_App.service')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='autodash_App.customervehicle')),
            ],
            options={
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['customer', 'scheduled_at'], name='autodash_Ap_custome_d2c6de_idx'), models.Index(fields=['branch', 'scheduled_at'], name='autodash_Ap_branch__2043c7_idx'), models.Index(fields=['status'], name='autodash_Ap_status_13bc96_idx')],
            },
        ),
    ]
