# Generated by Django 5.1.2 on 2025-12-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0062_maintenancelog_maintenanceexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='momo_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='momo_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='momo_number_network',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
