# Generated by Django 6.0.2 on 2026-02-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0063_branch_momo_name_branch_momo_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_class',
            field=models.CharField(blank=True, choices=[('Detailing', 'Detailing'), ('Non-Detailing', 'Non-Detailing')], default='Non-Detailing', max_length=100, null=True),
        ),
    ]
