# Generated by Django 6.0.2 on 2026-04-19 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0064_service_service_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerenderedorder',
            name='is_walkin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerenderedorder',
            name='walkin_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='servicerenderedorder',
            name='walkin_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicerenderedorder',
            name='walkin_vehicle_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autodash_App.vehiclegroup'),
        ),
        migrations.AddField(
            model_name='servicerenderedorder',
            name='walkin_vehicle_make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicerenderedorder',
            name='walkin_vehicle_plate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
