# Generated by Django 6.0.2 on 2026-04-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0065_servicerenderedorder_is_walkin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='alternate_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
