# Generated by Django 6.0.2 on 2026-04-19 15:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0066_branch_alternate_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringPaymentSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('base_amount', models.FloatField(help_text='The baseline amount due every time this triggers.')),
                ('apply_on', models.JSONField(default=list, help_text='List of weekdays (0=Mon … 6=Sun) this payment is due.')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_setups', to='autodash_App.branch')),
            ],
        ),
        migrations.CreateModel(
            name='DailyPaymentTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('base_amount', models.FloatField(default=0.0, help_text='What is due just for today')),
                ('brought_forward', models.FloatField(default=0.0, help_text='Unpaid debt rolled over from previous days')),
                ('total_target', models.FloatField(default=0.0, help_text='Base Amount + Brought Forward')),
                ('amount_paid', models.FloatField(default=0.0, help_text='How much was actually paid towards this today')),
                ('is_settled', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_targets', to='autodash_App.branch')),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_targets', to='autodash_App.recurringpaymentsetup')),
            ],
            options={
                'ordering': ['-date', 'setup__description'],
                'unique_together': {('setup', 'date')},
            },
        ),
    ]
