# Generated by Django 6.0.2 on 2026-04-19 17:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0068_productstocklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScorecardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('weight', models.FloatField(default=0.0, help_text='Fraction of the final score this category contributes (0.0 – 1.0).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Scorecard Category',
                'verbose_name_plural': 'Scorecard Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DailyScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('final_score', models.FloatField(default=0.0, help_text='Cached weighted score 0.0–1.0.')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecards', to='autodash_App.branch')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecards', to='autodash_App.worker')),
            ],
            options={
                'ordering': ['-date', 'worker__user__last_name'],
                'unique_together': {('worker', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ScorecardCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_points', models.FloatField(default=100.0, help_text='Full-marks value for this criterion.', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='autodash_App.scorecardcategory')),
            ],
            options={
                'ordering': ['category__display_order', 'display_order', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DailyScoreEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_awarded', models.FloatField(default=0.0)),
                ('reason', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scorecard_adjustments', to=settings.AUTH_USER_MODEL)),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='autodash_App.dailyscorecard')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='autodash_App.scorecardcriterion')),
            ],
            options={
                'ordering': ['criterion__category__display_order', 'criterion__display_order'],
                'unique_together': {('scorecard', 'criterion')},
            },
        ),
    ]
