# Generated by Django 6.0.2 on 2026-04-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0069_scorecardcategory_dailyscorecard_scorecardcriterion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecardcriterion',
            name='auto_source',
            field=models.CharField(blank=True, choices=[('', 'Manual (GM adjusts)'), ('orders', 'Auto — Orders actual / target'), ('services', 'Auto — Services actual / target')], default='', help_text="If set, this criterion is auto-computed from actual work vs worker's target.", max_length=20),
        ),
        migrations.AddField(
            model_name='worker',
            name='daily_orders_target',
            field=models.FloatField(default=0, help_text='Target number of service orders per day.'),
        ),
        migrations.AddField(
            model_name='worker',
            name='daily_services_target',
            field=models.FloatField(default=0, help_text='Target number of services rendered per day.'),
        ),
    ]
