# Generated by Django 6.0.2 on 2026-04-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0070_scorecardcriterion_auto_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrears',
            name='paid_cash_amount',
            field=models.FloatField(default=0.0, help_text='Portion of arrears paid in cash.'),
        ),
        migrations.AddField(
            model_name='arrears',
            name='paid_momo_amount',
            field=models.FloatField(default=0.0, help_text='Portion of arrears paid via MoMo.'),
        ),
        migrations.AddField(
            model_name='servicerenderedorder',
            name='momo_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='servicerenderedorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('loyalty', 'Loyalty Points'), ('subscription', 'Subscription'), ('cash', 'Cash'), ('momo', 'MoMo'), ('split', 'Cash + MoMo')], max_length=50, null=True),
        ),
    ]
