# Generated by Django 6.0.2 on 2026-07-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0071_arrears_paid_cash_amount_arrears_paid_momo_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerenderedorder',
            name='card_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='servicerenderedorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('loyalty', 'Loyalty Points'), ('subscription', 'Subscription'), ('cash', 'Cash'), ('momo', 'MoMo'), ('card', 'Card'), ('split', 'Split')], max_length=50, null=True),
        ),
    ]
