# Generated by Django 6.0.2 on 2026-08-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0072_servicerenderedorder_card_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='daily_value_target',
            field=models.FloatField(default=0, help_text='Target value (GHS) of services this worker is expected to generate per day.'),
        ),
        migrations.AlterField(
            model_name='scorecardcriterion',
            name='auto_source',
            field=models.CharField(blank=True, choices=[('', 'Manual (GM adjusts)'), ('orders', 'Auto — Orders actual / target'), ('services', 'Auto — Services actual / target'), ('value', 'Auto — Value (GHS) actual / target')], default='', help_text="If set, this criterion is auto-computed from actual work vs worker's target.", max_length=20),
        ),
    ]
