# Generated by Django 6.0.2 on 2026-08-27 20:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0073_worker_daily_value_target_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(default='units', help_text='Unit the balances are measured in, e.g. units, litres, GHS.', max_length=30)),
                ('cost_per_unit', models.FloatField(default=1.0, help_text='GHS per unit, used to book daily usage as an expense. Leave at 1.0 when the balance is already in GHS.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilities', to='autodash_App.branch')),
            ],
            options={
                'verbose_name_plural': 'Utilities',
                'ordering': ['branch__name', 'name'],
                'unique_together': {('branch', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UtilityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('opening_balance', models.FloatField(default=0.0)),
                ('purchase', models.FloatField(default=0.0)),
                ('closing_balance', models.FloatField(default=0.0)),
                ('usage', models.FloatField(default=0.0, editable=False)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility_readings', to='autodash_App.branch')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utility_readings', to=settings.AUTH_USER_MODEL)),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utility_reading', to='autodash_App.expense')),
                ('utility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='autodash_App.utility')),
            ],
            options={
                'ordering': ['-date', 'utility__name'],
                'unique_together': {('utility', 'date')},
            },
        ),
    ]
