# Generated by Django 6.0.2 on 2026-08-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0074_utility_utilityreading'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('operating', 'Operating'), ('other', 'Other')], default='other', help_text='Operating = day-to-day running cost (incl. utilities). Other = everything non-operational.', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_auto_generated',
            field=models.BooleanField(default=False),
        ),
    ]
