# Generated by Django 6.0.2 on 2026-08-27 21:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0075_expense_expense_type_expense_is_auto_generated'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRemittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('target_amount', models.FloatField(default=0.0)),
                ('brought_forward', models.FloatField(default=0.0, help_text='Unremitted balance carried in from previous days.')),
                ('total_due', models.FloatField(default=0.0, editable=False)),
                ('net_sales', models.FloatField(default=0.0, help_text='Recomputed through the day; frozen once the day is finalised.')),
                ('is_finalized', models.BooleanField(default=False, help_text='Set at day rollover; stops net sales from moving.')),
                ('amount_remitted', models.FloatField(default=0.0, editable=False)),
                ('surplus', models.FloatField(default=0.0, editable=False)),
                ('is_settled', models.BooleanField(default=False, editable=False)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remittances', to='autodash_App.branch')),
            ],
            options={
                'ordering': ['-date', 'branch__name'],
                'unique_together': {('branch', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RemittancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('cash', 'Cash'), ('momo', 'MoMo'), ('bank', 'Bank')], max_length=10)),
                ('amount', models.FloatField(default=0.0)),
                ('reference', models.CharField(blank=True, default='', help_text='Optional: teller/transaction reference.', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remittance_payments', to=settings.AUTH_USER_MODEL)),
                ('remittance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='autodash_App.dailyremittance')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RemittanceSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_amount', models.FloatField(default=0.0, help_text='Baseline amount expected to be remitted each operating day.')),
                ('apply_on', models.JSONField(blank=True, default=list, help_text='Weekdays this target applies (0=Mon … 6=Sun). Empty means every day.')),
                ('primary_source', models.CharField(choices=[('cash', 'Cash'), ('momo', 'MoMo'), ('bank', 'Bank')], default='cash', help_text='Where the target portion is remitted by default. Always editable on the day.', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remittance_setup', to='autodash_App.branch')),
            ],
            options={
                'ordering': ['branch__name'],
            },
        ),
    ]
