# Generated by Django 6.0.2 on 2026-09-09 17:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0076_dailyremittance_remittancepayment_remittancesetup'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='other_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='autodash_App.otherservice'),
        ),
        migrations.AddField(
            model_name='otherservice',
            name='commission_amount',
            field=models.FloatField(blank=True, help_text='Cached commission pool; maintained by allocate_commission().', null=True),
        ),
        migrations.AddField(
            model_name='otherservice',
            name='commission_rate',
            field=models.FloatField(default=0.0, help_text='Percent of the amount shared among the service-provider workers on this job.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='commission',
            name='service_rendered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='autodash_App.servicerendered'),
        ),
        migrations.AddConstraint(
            model_name='commission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('other_service__isnull', True), ('service_rendered__isnull', False)), models.Q(('other_service__isnull', False), ('service_rendered__isnull', True)), _connector='OR'), name='commission_exactly_one_source'),
        ),
    ]
