# Generated by Django 6.0.2 on 2026-09-09 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0077_commission_other_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrears',
            name='other_service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrears', to='autodash_App.otherservice'),
        ),
        migrations.AddField(
            model_name='otherservice',
            name='card_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='otherservice',
            name='cash_paid',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='otherservice',
            name='momo_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='otherservice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('momo', 'MoMo'), ('card', 'Card'), ('split', 'Split')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='arrears',
            name='service_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrears', to='autodash_App.servicerenderedorder'),
        ),
        migrations.AddConstraint(
            model_name='arrears',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('other_service__isnull', True), ('service_order__isnull', False)), models.Q(('other_service__isnull', False), ('service_order__isnull', True)), _connector='OR'), name='arrears_exactly_one_source'),
        ),
    ]
