# Generated by Django 6.0.2 on 2026-09-09 17:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0078_arrears_other_service_otherservice_card_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddConstraint(
            model_name='commission',
            constraint=models.UniqueConstraint(fields=('worker', 'service_rendered'), name='commission_unique_worker_per_line'),
        ),
        migrations.AddConstraint(
            model_name='commission',
            constraint=models.UniqueConstraint(fields=('worker', 'other_service'), name='commission_unique_worker_per_other_service'),
        ),
    ]
