# Generated by Django 6.0.2 on 2026-09-09 18:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0079_alter_commission_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_threshold', models.FloatField(default=0.0, help_text='Warn once the float falls to or below this. e.g. hold GHS 100, warn at GHS 20.')),
                ('balance', models.FloatField(default=0.0, editable=False, help_text='Cached float balance; rebuilt by recalculate().')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='petty_cash', to='autodash_App.branch')),
            ],
            options={
                'verbose_name': 'Petty cash account',
                'verbose_name_plural': 'Petty cash accounts',
                'ordering': ['branch__name'],
            },
        ),
        migrations.CreateModel(
            name='PettyCashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('topup', 'Top-up'), ('expense', 'Expense'), ('adjustment', 'Adjustment')], max_length=20)),
                ('amount', models.FloatField(help_text='Positive figure. The kind decides whether it goes in or out.', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('direction', models.SmallIntegerField(default=1, help_text='+1 money in, -1 money out. Only meaningful for adjustments; top-ups and expenses set it from their kind.')),
                ('signed_amount', models.FloatField(default=0.0, editable=False)),
                ('balance_after', models.FloatField(default=0.0, editable=False, help_text='Float balance immediately after this movement.')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='autodash_App.pettycashaccount')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petty_cash_transactions', to='autodash_App.branch')),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petty_cash_transaction', to='autodash_App.expense')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Petty cash movement',
                'verbose_name_plural': 'Petty cash movements',
                'ordering': ['-date', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('direction', 1), ('direction', -1), _connector='OR'), name='petty_cash_direction_is_plus_or_minus_one')],
            },
        ),
    ]
