# Generated by Django 6.0.2 on 2026-09-09 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0080_pettycashaccount_pettycashtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycashtransaction',
            name='utility_reading',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petty_cash_transaction', to='autodash_App.utilityreading'),
        ),
        migrations.AlterField(
            model_name='pettycashtransaction',
            name='kind',
            field=models.CharField(choices=[('topup', 'Top-up'), ('reimbursement', 'Reimbursement'), ('expense', 'Expense'), ('adjustment', 'Adjustment')], max_length=20),
        ),
    ]
