# Generated by Django 6.0.2 on 2026-09-09 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0081_pettycashtransaction_utility_reading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='topup_reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topup_expenses', to='autodash_App.utilityreading'),
        ),
        migrations.AddField(
            model_name='utility',
            name='topup_keywords',
            field=models.CharField(blank=True, default='', help_text="Comma-separated aliases used to spot a top-up expense for this utility, e.g. 'ECG, power, light' for Electricity. The utility's own name always matches.", max_length=255),
        ),
        migrations.AddField(
            model_name='utilityreading',
            name='auto_purchase',
            field=models.FloatField(default=0.0, editable=False, help_text='Credit bought, totalled from matching top-up expenses.'),
        ),
        migrations.AlterField(
            model_name='utilityreading',
            name='purchase',
            field=models.FloatField(default=0.0, help_text='Credit bought and entered by hand on this page.'),
        ),
    ]
