# Generated by Django 6.0.2 on 2026-09-09 20:17
#
# Petty cash becomes ONE cumulative float instead of one per branch. Cash is put
# down once and every branch spends from the same pot, so the branch moves off
# the account and onto the movements.

import django.db.models.deletion
from django.db import migrations, models


def merge_floats(apps, schema_editor):
    """
    Fold any existing per-branch floats into a single one.

    Every movement is re-pointed at the survivor and keeps its own branch, so
    nothing is lost: the combined balance is the sum of what the separate tins
    held, and each branch's history stays attributable. Runs before the branch
    column is dropped, while the rows can still be told apart.
    """
    PettyCashAccount = apps.get_model("autodash_App", "PettyCashAccount")
    PettyCashTransaction = apps.get_model("autodash_App", "PettyCashTransaction")

    accounts = list(PettyCashAccount.objects.order_by("pk"))
    if len(accounts) <= 1:
        return

    survivor = accounts[0]
    doomed = accounts[1:]

    # A movement without a branch of its own inherits the one whose tin it was
    # in, so a branch's draw is still countable afterwards.
    for account in accounts:
        PettyCashTransaction.objects.filter(
            account=account, branch__isnull=True
        ).update(branch=account.branch_id)

    PettyCashTransaction.objects.filter(account__in=doomed).update(account=survivor)

    survivor.balance = sum(a.balance or 0.0 for a in accounts)
    # Keep the most cautious threshold rather than an arbitrary one.
    survivor.low_threshold = max((a.low_threshold or 0.0) for a in accounts)
    survivor.is_active = any(a.is_active for a in accounts)
    survivor.save()

    PettyCashAccount.objects.filter(pk__in=[a.pk for a in doomed]).delete()


def unmerge(apps, schema_editor):
    """Irreversible in any meaningful sense; separate tins cannot be rebuilt."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0083_seed_utility_topup_keywords'),
    ]

    operations = [
        # The movement's branch has to be nullable before the merge can lean on it.
        migrations.AlterField(
            model_name='pettycashtransaction',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petty_cash_transactions', to='autodash_App.branch'),
        ),
        migrations.RunPython(merge_floats, unmerge),
        migrations.AlterModelOptions(
            name='pettycashaccount',
            options={'verbose_name': 'Petty cash float', 'verbose_name_plural': 'Petty cash float'},
        ),
        migrations.RemoveField(
            model_name='pettycashaccount',
            name='branch',
        ),
    ]
