# Generated by Django 6.0.2 on 2026-09-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodash_App', '0084_alter_pettycashaccount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyremittance',
            name='carried_forward',
            field=models.FloatField(default=0.0, editable=False, help_text="How much of this day's balance a later day has taken on as its brought_forward. Once carried, the debt lives there, not here."),
        ),
    ]
